#!/bin/sh
cons="  root root 622"
disk="  root root 660"
null="  root root 666"
urandom="  root root  644"
mkdev () {    # usage: mkdev name [bcu] major minor owner group mode
        if [ "$opt_v" ]
        then    if [ "$opt_d" ]
                then    echo "sudo rm -f $1"
                else    echo "$1        = $2 $3 $4 $5:$6 $7"
                fi
        fi
        [ ! "$opt_n" ] && sudo rm -f $1 &&
        [ ! "$opt_d" ] && sudo mknod $1 $2 $3 $4 &&
                sudo chown $5:$6 $1 &&
                sudo chmod $7 $1
}  
cd $1

mkdev 	dev/ram  	b	1	1	$disk 
mkdev 	dev/ram0 	b	1	0 	$disk
mkdev 	dev/ram1 	b 	1 	1	$disk 
mkdev 	dev/ram2 	b 	1 	2 	$disk
mkdev 	dev/ram3 	b 	1 	3 	$disk

mkdev   dev/mem     c   1   1   $disk
mkdev 	dev/kmem 	c 	1 	2 	$null
mkdev 	dev/null 	c 	1 	3 	$null
mkdev 	dev/random 	c 	1 	8 	$urandom
mkdev 	dev/urandom 	c 	1 	9 	$urandom

mkdev   dev/sda         b       8       0       $disk
mkdev   dev/sda1        b       8       1       $disk
mkdev   dev/sda2        b       8       2       $disk
mkdev   dev/sda3        b       8       3       $disk
mkdev   dev/sda4        b       8       4       $disk

mkdev   dev/sdb         b       8       16      $disk
mkdev   dev/sdb1        b       8       17      $disk
mkdev   dev/sdb2        b       8       18      $disk
mkdev   dev/sdb3        b       8       19      $disk
mkdev   dev/sdb4        b       8       20      $disk

mkdev   dev/sdc         b       8       32      $disk
mkdev   dev/sdc1        b       8       33      $disk
mkdev   dev/sdc2        b       8       34      $disk
mkdev   dev/sdc3        b       8       35      $disk
mkdev   dev/sdc4        b       8       36      $disk

mkdev   dev/sdd         b       8       48      $disk
mkdev   dev/sdd1        b       8       49      $disk
mkdev   dev/sdd2        b       8       50      $disk
mkdev   dev/sdd3        b       8       51      $disk
mkdev   dev/sdd4        b       8       52      $disk

mkdev 	dev/ptyp0 	c 	2 	0 	$urandom
mkdev 	dev/ptyp1 	c 	2 	1	$urandom

mkdev 	dev/ttyp0 	c 	3 	0 	$urandom
mkdev 	dev/ttyp1 	c 	3 	1 	$urandom

mkdev 	dev/ptmx 	c 	5 	2 	$null

mkdev 	dev/tty0 	c 	4 	0 	$cons
mkdev 	dev/tty1 	c 	4 	1 	$cons
mkdev 	dev/ttyS0 	c 	4 	64 	$cons
mkdev 	dev/ttyS1 	c 	4 	65 	$cons

mkdev 	dev/tty 	c 	5	0 	$cons
mkdev 	dev/console 	c 	5 	1 	$cons

mkdev   dev/pts/0       c       136     0       $cons
mkdev   dev/pts/1       c       136     1       $cons
mkdev   dev/pts/2       c       136     2       $cons
mkdev   dev/pts/3       c       136     3       $cons

mkdev 	dev/ppp 	c 	108 	0 	$cons
mkdev 	dev/spiS0 	c 	217 	0 	$cons
mkdev 	dev/i2cM0 	c 	218 	0 	$cons

mkdev 	dev/flash0	c 	200 	0 	$cons
mkdev 	dev/swnat0	c 	210 	0 	$cons
mkdev 	dev/hwnat0	c 	220 	0 	$cons
mkdev 	dev/acl0	c 	230 	0 	$cons
mkdev 	dev/ac0		c 	240 	0 	$cons
mkdev 	dev/mtr0	c 	250 	0 	$cons
mkdev   dev/nvram   	c   	251     0   	$cons
mkdev 	dev/gpio	c 	252 	0 	$cons
mkdev 	dev/rdm0 	c 	253 	0 	$cons
mkdev   dev/PCM         c       233     0       $cons
mkdev   dev/I2S         c       234     0       $cons

#MTD devices
for a in `seq 0 4` ; do
    if [ \! -c dev/mtd$a ]; then
	sudo mknod dev/mtd$a c 90 `expr $a + $a`;
    fi;

    if [ \! -c dev/mtdr$a ]; then
	sudo mknod dev/mtdr$a c 90 `expr $a + $a + 1`;
    fi;
    if [ \! -b dev/mtdblock$a ]; then
	sudo mknod dev/mtdblock$a b 31 $a;
    fi;
done	
